# -------------------------------------------------------------------
name: CI
# -------------------------------------------------------------------
# Пайплайн выполняется при создании PR в main и при пуше в любую ветку
# -------------------------------------------------------------------
on:
  push:
  pull_request:
    branches: [ main ]
# -------------------------------------------------------------------
# Выполняется на Windows, чтобы полностью соответствовать dev окружению
# -------------------------------------------------------------------
jobs:
  build:
    runs-on: windows-latest
    steps:
# -------------------------------------------------------------------
# Скачать код из репозитория
# -------------------------------------------------------------------
      - uses: actions/checkout@v4
# -------------------------------------------------------------------
# Скачать java и gradle
# -------------------------------------------------------------------
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
# -------------------------------------------------------------------
# Запуск тестов и сборки для всех проектов
# -------------------------------------------------------------------
      - name: Build and test all labs
        run: ./gradlew.bat build
# -------------------------------------------------------------------
